### ISSUE TITLE
Questions regarding the code

### ISSUE THREAD

**Issue by aservantofhismajesty** [DarkSpiritz/DarkSpiritz3#1]
Hi, I've started working on a couple of changes that I'd eventually like to send a PR. But first I wanted to understand some of the reasoning behind the code. 

In [main.py](https://github.com/DarkSpiritz/DarkSpiritz3/blob/master/main.py) when the code needs to call another program, it sometimes uses `os.system()` and other times it uses `subprocess.call` even though, in this case, they have the exact same function. 

Question:
Would there be any problems, in your opinion, in changing all of the current usages of `os.system()` to `subprocess.call`?

Question:
In the aforementioned file in the `main` function which starts at [line 134](https://github.com/DarkSpiritz/DarkSpiritz3/blob/master/main.py#L134) there is a great amount of lines that appear to be parsing the commands given by the user. I think a better approach would be to map the necessary functions to a dictionary, i.e., suppose we were to refactor [line 181](https://github.com/DarkSpiritz/DarkSpiritz3/blob/master/main.py#L181) to follow this approach, what I have in mind would be something of the sort:

```python3
valid_functions = {'show': showlist,
                            'help': help.help} // etc..

elif terminal[0:] == 'show':
    valid_functions[terminal[0:]]()
```

Please note that the above suggestion can be simplified even more, but I hope you understand what I mean.

Question:

The parsing of the commands given by the user seems to be done manually and in a very verbose manner, I suggest we create a function to parse the commands and execute their respective actions.

Question:

In [line 222](https://github.com/DarkSpiritz/DarkSpiritz3/blob/master/main.py#L227) all of these if statements could be reduced to a single one if the strings were stored in a list. Would this be acceptable?

There are more things which I'd like to change, but I shall mention them again in the future once I've solved the current problems that I've found.

**Comment by aservantofhismajesty** [comment]
A couple more things to note... throughout the code there seems to be a lot of statements printing errors, info, warnings, etc., perhaps it would be better to either use a logging module or to standardize this API so it could be more easily used around.

**Comment by aservantofhismajesty** [comment]
I went ahead and made some of the changes that I initially thought about. Before I continue, I'd like some feedback from the project maintainers. As it stands, my fork does not currently work (nor was it supposed to), but I think it shows the gist of what I'm interested in changing in the code, but I'd like feedback before I commit to it. Thanks.

**Comment by Ryan0x1** [comment]
Hey sciophobia, Due to many users downvoting DarkSpiritz because of python2. We are going to port the original source to python3. If you pull your requests to this current repo and we will be able to start porting it over. 

Thanks.

**Comment by aservantofhismajesty** [comment]
Thanks - I'll test my changes in a Linux environment and once everything works I'll send a PR.

**Comment by M4cs** [comment]
I think your idea for putting commands into some sort of dictionary is great and will help clean up the code. To your other points i think theyre all great and could help by being implemented. We had logging at one point and it was wonky so we decided to just remove it. Continue to work on your Fork and when you make the PR we will most likely merge if everything is working! Like Ryan said we are making Python3 the main version soon so any contribution would be GREATLY appreciated.
